version: 2.0
jobs: 
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run: 
          name: Restore Packages
          command: dotnet restore ./src/NswLicensePlateLookup
      - run: 
          name: Build 
          command: dotnet build ./src/NswLicensePlateLookup
      - run: 
          name: Test 
          command: dotnet test ./tst/NswLicensePlateLookupTests
